
#ifndef E_H
#define E_H

#define ui64		  unsigned __int64
#define si64		    signed __int64
#define ui32		  unsigned long  int
#define si32		    signed long  int
#define ui16		  unsigned short int
#define si16		    signed short int
#define ui8		  unsigned	char
#define si8		    signed	char

#define real32			       float
#define real64			      double

typedef short int sym;

#define until(n) while (!(n))
#define unless(n) if (!(n))

#define true 1
#define TRUE 1
#define True 1
#define false 0
#define FALSE 0
#define False 0

#endif

